- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: Create tomcat container
    community.docker.docker_container:
      image: tomcat:9.0
      name: tomcat
      state: present
      ports:
        - "8080:8080"
  
  - name: Copy jenkins.war in tomcat
    community.docker.docker_container_copy_into:
      container: tomcat
      path: jenkins.war
      container_path: /usr/local/tomcat/webapps/jenkins.war

  - name: Copy files from directory webapps.dist to webapps 
    community.docker.docker_container_exec:
      container: tomcat
      command: /bin/bash -c "cp -R webapps.dist/* webapps/"
      chdir: /usr/local/tomcat/
    register: result

  - name: Create nginx container
    community.docker.docker_container:
      image: nginx:mainline-alpine
      name: nginx
      recreate: true
      state: started
      ports:
        - "80:80"
 
  - name: Copy nginx.conf into nginx
    community.docker.docker_container_copy_into:
      container: nginx
      path: nginx.conf
      container_path: /etc/nginx/conf.d/default.conf


  - name: Check nginx config and reload
    community.docker.docker_container_exec:
      container: nginx
      command: /bin/sh -c "nginx -t && nginx -s reload"
    register: result

