- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: Create tomcat container
    community.docker.docker_container:
      image: tomcat:9.0
      name: tomcat
      state: started
      recreate: false
      ports:
        - "8080:8080"
  
  - name: Copy jenkins.war in tomcat
    community.docker.docker_container_copy_into:
      container: tomcat
      path: jenkins.war
      container_path: /usr/local/tomcat/webapps/jenkins.war

  - name: Copy files from directory webapps.dist to webapps 
    community.docker.docker_container_exec:
      container: tomcat
      command: /bin/bash -c "cp -R webapps.dist/* webapps/"
      chdir: /usr/local/tomcat/
    register: result

  - name: Create nginx container
    community.docker.docker_container:
      image: nginx:mainline-alpine
      name: nginx
      state: started
      recreate: false
      ports:
        - "80:80"
 

  # You can change the ip address in nginx.conf in main directory of repository
  
  - name: Copy nginx.conf into nginx
    community.docker.docker_container_copy_into:
      container: nginx
      path: nginx.conf
      container_path: /etc/nginx/conf.d/default.conf


  - name: Check nginx config and reload
    community.docker.docker_container_exec:
      container: nginx
      command: /bin/sh -c "nginx -t && nginx -s reload"
    register: result


  - name: Create a directory for nginx-config backup file
    ansible.builtin.file:
      path: /nginx/config-backup
      state: directory
      mode: '0755'

  - name: Create backup script for nginx config
    copy:
      content: |
        #!/bin/bash
        /usr/bin/docker cp nginx:/etc/nginx/conf.d/default.conf /nginx/config-backup/
      dest: /nginx/config-backup/backup-script.sh
      mode: a+x

  - name: Creates a cron file under /etc/cron.d
    ansible.builtin.cron:
      name: backup nginx config
      weekday: "*"
      hour: "*"
      minute: "*"
      user: root
      job: "/bin/bash /nginx/config-backup/backup-script.sh"
      cron_file: nginx-backup-config