- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: Create nginx container
    community.docker.docker_container:
      image: nginx:mainline-alpine
      name: nginx
      recreate: true
      state: started
      ports:
        - "80:80"

  - name: Copy a file into the container
    community.docker.docker_container_copy_into:
      container: nginx
      path: ./nginx/nginx.conf
      container_path: /etc/nginx/conf.d/default.conf

  - name: Reload nginx configuration
    shell: docker exec nginx nginx -t; docker exec nginx nginx -s reload


  - name: Run tomcat + jenkins
    shell: docker-compose -f tomcat+jenkins.yml up -d